# This workflow installs dependencies, builds the app, and deploys to GitHub Pages
# See: https://docs.github.com/actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x] # Use Node.js 24

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Enables dependency caching

      - name: Fetch data, install dependencies and build application
        run: |
          sudo apt install python3-pip
          pip install gdown
          gdown https://drive.google.com/uc?id=1Ig_GUZn222UGk81950Qg8_vjvsqSwm_d
          mkdir data
          mv schools.json data

          # More robust install command with fallback
          npm ci --prefer-offline --no-audit --no-fund

          npm run build
          rm -rf data
        env:
          NEXT_PUBLIC_BASE_PATH: https://schools.smartchance.org

      - name: Add .nojekyll to prevent Jekyll processing on GitHub Pages
        run: touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # Target branch for deployment
          folder: out # Build output folder
